//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Boltpay.SDK.Models.Components
{
    using Boltpay.SDK.Models.Components;
    using Boltpay.SDK.Utils;
    using Newtonsoft.Json;
    
    public class AccountTestCreationDataOutput
    {

        [JsonProperty("email")]
        public string Email { get; set; } = default!;

        [JsonProperty("email_state")]
        public EmailState EmailState { get; set; } = default!;

        [JsonProperty("phone")]
        public string Phone { get; set; } = default!;

        [JsonProperty("phone_state")]
        public PhoneState PhoneState { get; set; } = default!;

        [JsonProperty("otp_code")]
        public string OtpCode { get; set; } = default!;

        [JsonProperty("oauth_code")]
        public string OauthCode { get; set; } = default!;
    }
}