//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Boltpay.SDK.Models.Components
{
    using Boltpay.SDK.Utils;
    using Newtonsoft.Json;
    
    public class AccountTestPhoneData
    {

        /// <summary>
        /// A random, fictitious, unassigned phone number.
        /// </summary>
        [JsonProperty("phone")]
        public string Phone { get; set; } = default!;
    }
}