//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Boltpay.SDK.Models.Components
{
    using Boltpay.SDK.Models.Components;
    using Boltpay.SDK.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// An address saved on an account, i.e. a physical address plus any additional account-specific metadata.
    /// </summary>
    public class AddressListing
    {

        /// <summary>
        /// The address&apos;s unique identifier.
        /// </summary>
        [JsonProperty("id")]
        public string? Id { get; set; }

        /// <summary>
        /// The first name of the person associated with this address.
        /// </summary>
        [JsonProperty("first_name")]
        public string FirstName { get; set; } = default!;

        /// <summary>
        /// The last name of the person associated with this address.
        /// </summary>
        [JsonProperty("last_name")]
        public string LastName { get; set; } = default!;

        /// <summary>
        /// The company associated with this address.
        /// </summary>
        [JsonProperty("company")]
        public string? Company { get; set; }

        /// <summary>
        /// The street address associated with this address.
        /// </summary>
        [JsonProperty("street_address1")]
        public string StreetAddress1 { get; set; } = default!;

        /// <summary>
        /// Any additional, optional, street address information associated with this address.
        /// </summary>
        [JsonProperty("street_address2")]
        public string? StreetAddress2 { get; set; }

        /// <summary>
        /// The locality (e.g. city, town, etc...) associated with this address.
        /// </summary>
        [JsonProperty("locality")]
        public string Locality { get; set; } = default!;

        /// <summary>
        /// The postal code associated with this address.
        /// </summary>
        [JsonProperty("postal_code")]
        public string PostalCode { get; set; } = default!;

        /// <summary>
        /// The region or administrative area (e.g. state, province, county, etc...) associated with this address.
        /// </summary>
        [JsonProperty("region")]
        public string? Region { get; set; }

        /// <summary>
        /// The country (in its ISO 3166 alpha-2 format) associated with this address.
        /// </summary>
        [JsonProperty("country_code")]
        public CountryCode CountryCode { get; set; } = default!;

        /// <summary>
        /// The email address associated with this address.
        /// </summary>
        [JsonProperty("email")]
        public string? Email { get; set; }

        /// <summary>
        /// The phone number associated with this address.
        /// </summary>
        [JsonProperty("phone")]
        public string? Phone { get; set; }

        /// <summary>
        /// Whether or not this is the default address saved.
        /// </summary>
        [JsonProperty("is_default")]
        public bool? IsDefault { get; set; }
    }
}