//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Boltpay.SDK.Models.Components
{
    using Boltpay.SDK.Models.Components;
    using Boltpay.SDK.Utils;
    using Newtonsoft.Json;
    
    public class AddressReferenceId
    {

        /// <summary>
        /// The type of address reference
        /// </summary>
        [JsonProperty(".tag")]
        public AddressReferenceIdTag DotTag { get; set; } = default!;

        /// <summary>
        /// The address&apos;s ID
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; } = default!;
    }
}