//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Boltpay.SDK.Models.Components
{
    using Boltpay.SDK.Models.Components;
    using Boltpay.SDK.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// A monetary amount, i.e. a base unit amount and a supported currency.
    /// </summary>
    public class Amount
    {

        /// <summary>
        /// A supported currency.
        /// </summary>
        [JsonProperty("currency")]
        public Currency Currency { get; set; } = default!;

        /// <summary>
        /// A monetary amount, represented in its base units (e.g. USD/EUR cents).
        /// </summary>
        [JsonProperty("units")]
        public long Units { get; set; } = default!;
    }
}