//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Boltpay.SDK.Models.Components
{
    using Boltpay.SDK.Models.Components;
    using Boltpay.SDK.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public class Cart
    {

        /// <summary>
        /// This value is used by Bolt as an external reference to a given order. This reference must be unique per successful transaction.
        /// </summary>
        [JsonProperty("order_reference")]
        public string OrderReference { get; set; } = default!;

        /// <summary>
        /// Used optionally to pass additional information like order numbers or other IDs as needed.
        /// </summary>
        [JsonProperty("order_description")]
        public string? OrderDescription { get; set; }

        /// <summary>
        /// A shopper-facing identifier corresponding to the order reference associated with this transaction.
        /// </summary>
        [JsonProperty("display_id")]
        public string? DisplayId { get; set; }

        [JsonProperty("shipments")]
        public List<CartShipment>? Shipments { get; set; }

        [JsonProperty("discounts")]
        public List<CartDiscount>? Discounts { get; set; }

        [JsonProperty("items")]
        public List<CartItem>? Items { get; set; }

        /// <summary>
        /// A monetary amount, i.e. a base unit amount and a supported currency.
        /// </summary>
        [JsonProperty("total")]
        public Amount Total { get; set; } = default!;

        /// <summary>
        /// A monetary amount, i.e. a base unit amount and a supported currency.
        /// </summary>
        [JsonProperty("tax")]
        public Amount Tax { get; set; } = default!;
    }
}