//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Boltpay.SDK.Models.Components
{
    using Boltpay.SDK.Models.Components;
    using Boltpay.SDK.Utils;
    using Newtonsoft.Json;
    
    public class CartDiscount
    {

        /// <summary>
        /// A monetary amount, i.e. a base unit amount and a supported currency.
        /// </summary>
        [JsonProperty("amount")]
        public Amount Amount { get; set; } = default!;

        /// <summary>
        /// Discount code.
        /// </summary>
        [JsonProperty("code")]
        public string? Code { get; set; }

        /// <summary>
        /// Used to provide a link to additional details, such as a landing page, associated with the discount offering.
        /// </summary>
        [JsonProperty("details_url")]
        public string? DetailsUrl { get; set; }
    }
}