//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Boltpay.SDK.Models.Components
{
    using Boltpay.SDK.Models.Components;
    using Boltpay.SDK.Utils;
    using Newtonsoft.Json;
    
    public class CartItem
    {

        /// <summary>
        /// The name of a given item.
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        /// <summary>
        /// This value is used by Bolt as an external reference to a given item.
        /// </summary>
        [JsonProperty("reference")]
        public string Reference { get; set; } = default!;

        /// <summary>
        /// A human-readable description of this cart item.
        /// </summary>
        [JsonProperty("description")]
        public string? Description { get; set; }

        /// <summary>
        /// A monetary amount, i.e. a base unit amount and a supported currency.
        /// </summary>
        [JsonProperty("total_amount")]
        public Amount TotalAmount { get; set; } = default!;

        /// <summary>
        /// The item&apos;s unit price, i.e. the cost of a single item exclusive of tax and discounts.
        /// </summary>
        [JsonProperty("unit_price")]
        public long UnitPrice { get; set; } = default!;

        /// <summary>
        /// The number of units that comprise this cart item.
        /// </summary>
        [JsonProperty("quantity")]
        public long Quantity { get; set; } = default!;

        /// <summary>
        /// Used to provide a link to the image associated with the item.
        /// </summary>
        [JsonProperty("image_url")]
        public string? ImageUrl { get; set; }
    }
}