//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Boltpay.SDK.Models.Components
{
    using Boltpay.SDK.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// The credit card&apos;s network.
    /// </summary>
    public enum CreditCardNetwork
    {
        [JsonProperty("visa")]
        Visa,
        [JsonProperty("mastercard")]
        Mastercard,
        [JsonProperty("amex")]
        Amex,
        [JsonProperty("discover")]
        Discover,
        [JsonProperty("jcb")]
        Jcb,
        [JsonProperty("unionpay")]
        Unionpay,
        [JsonProperty("alliancedata")]
        Alliancedata,
        [JsonProperty("citiplcc")]
        Citiplcc,
    }

    public static class CreditCardNetworkExtension
    {
        public static string Value(this CreditCardNetwork value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static CreditCardNetwork ToEnum(this string value)
        {
            foreach(var field in typeof(CreditCardNetwork).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is CreditCardNetwork)
                    {
                        return (CreditCardNetwork)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum CreditCardNetwork");
        }
    }

}