//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Boltpay.SDK.Models.Components
{
    using Boltpay.SDK.Models.Components;
    using Boltpay.SDK.Utils;
    using Newtonsoft.Json;
    
    public class PaymentInitializeRequest
    {

        [JsonProperty("cart")]
        public Cart Cart { get; set; } = default!;

        [JsonProperty("payment_method")]
        public PaymentMethodExtended PaymentMethod { get; set; } = default!;

        public PaymentMethodReference? GetPaymentMethodId()
        {
            return PaymentMethod.PaymentMethodReference;
        }

        public PaymentMethodCreditCardInput? GetPaymentMethodCreditCard()
        {
            return PaymentMethod.PaymentMethodCreditCardInput;
        }

        public PaymentMethodPaypal? GetPaymentMethodPaypal()
        {
            return PaymentMethod.PaymentMethodPaypal;
        }

        public PaymentMethodAffirm? GetPaymentMethodAffirm()
        {
            return PaymentMethod.PaymentMethodAffirm;
        }

        public PaymentMethodAfterpay? GetPaymentMethodAfterpay()
        {
            return PaymentMethod.PaymentMethodAfterpay;
        }

        public PaymentMethodKlarna? GetPaymentMethodKlarna()
        {
            return PaymentMethod.PaymentMethodKlarna;
        }

        public PaymentMethodKlarnaAccount? GetPaymentMethodKlarnaAccount()
        {
            return PaymentMethod.PaymentMethodKlarnaAccount;
        }

        public PaymentMethodKlarnaPaynow? GetPaymentMethodKlarnaPaynow()
        {
            return PaymentMethod.PaymentMethodKlarnaPaynow;
        }
    }
}