//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Boltpay.SDK.Models.Components
{
    using Boltpay.SDK.Models.Components;
    using Boltpay.SDK.Utils;
    using Newtonsoft.Json;
    
    public class PaymentMethodCreditCard
    {

        [JsonProperty(".tag")]
        public Models.Components.DotTag DotTag { get; set; } = default!;

        [JsonProperty("id")]
        public string? Id { get; set; }

        [JsonProperty("billing_address")]
        public AddressReference BillingAddress { get; set; } = default!;

        public AddressReferenceId? GetBillingAddressId()
        {
            return BillingAddress.AddressReferenceId;
        }

        public AddressReferenceExplicit? GetBillingAddressExplicit()
        {
            return BillingAddress.AddressReferenceExplicit;
        }

        /// <summary>
        /// The credit card&apos;s network.
        /// </summary>
        [JsonProperty("network")]
        public CreditCardNetwork Network { get; set; } = default!;

        /// <summary>
        /// The account number&apos;s last four digits.
        /// </summary>
        [JsonProperty("last4")]
        public string Last4 { get; set; } = default!;

        /// <summary>
        /// The expiration date, in YYYY-MM format.
        /// </summary>
        [JsonProperty("expiration")]
        public string Expiration { get; set; } = default!;
    }
}