//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Boltpay.SDK.Models.Components
{
    using Boltpay.SDK.Utils;
    using Newtonsoft.Json;
    using System;
    
    public enum PaymentMethodPaypalTag
    {
        [JsonProperty("paypal")]
        Paypal,
    }

    public static class PaymentMethodPaypalTagExtension
    {
        public static string Value(this PaymentMethodPaypalTag value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static PaymentMethodPaypalTag ToEnum(this string value)
        {
            foreach(var field in typeof(PaymentMethodPaypalTag).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is PaymentMethodPaypalTag)
                    {
                        return (PaymentMethodPaypalTag)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum PaymentMethodPaypalTag");
        }
    }

}