//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Boltpay.SDK.Models.Components
{
    using Boltpay.SDK.Models.Components;
    using Boltpay.SDK.Utils;
    using Newtonsoft.Json;
    
    public class PaymentMethodPaypal
    {

        [JsonProperty(".tag")]
        public PaymentMethodPaypalTag DotTag { get; set; } = default!;

        /// <summary>
        /// Redirect URL for successful PayPal transaction.
        /// </summary>
        [JsonProperty("success_url")]
        public string SuccessUrl { get; set; } = default!;

        /// <summary>
        /// Redirect URL for canceled PayPal transaction.
        /// </summary>
        [JsonProperty("cancel_url")]
        public string CancelUrl { get; set; } = default!;
    }
}