//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Boltpay.SDK.Models.Components
{
    using Boltpay.SDK.Models.Components;
    using Boltpay.SDK.Utils;
    using Newtonsoft.Json;
    
    public class PaymentActionRequest
    {

        [JsonProperty(".tag")]
        public PaymentActionRequestTag DotTag { get; set; } = default!;

        /// <summary>
        /// Optional redirect result token required for an APM payment (excluding PayPal).
        /// </summary>
        [JsonProperty("redirect_result")]
        public string? RedirectResult { get; set; }
    }
}