//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Boltpay.SDK.Models.Components
{
    using Boltpay.SDK.Models.Components;
    using Boltpay.SDK.Utils;
    using Newtonsoft.Json.Linq;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;
    using System;
    

    public class PaymentMethodExtendedType
    {
        private PaymentMethodExtendedType(string value) { Value = value; }

        public string Value { get; private set; }
        
        public static PaymentMethodExtendedType Id { get { return new PaymentMethodExtendedType("id"); } }
        public static PaymentMethodExtendedType CreditCard { get { return new PaymentMethodExtendedType("credit_card"); } }
        public static PaymentMethodExtendedType Paypal { get { return new PaymentMethodExtendedType("paypal"); } }
        public static PaymentMethodExtendedType Affirm { get { return new PaymentMethodExtendedType("affirm"); } }
        public static PaymentMethodExtendedType Afterpay { get { return new PaymentMethodExtendedType("afterpay"); } }
        public static PaymentMethodExtendedType Klarna { get { return new PaymentMethodExtendedType("klarna"); } }
        public static PaymentMethodExtendedType KlarnaAccount { get { return new PaymentMethodExtendedType("klarna_account"); } }
        public static PaymentMethodExtendedType KlarnaPaynow { get { return new PaymentMethodExtendedType("klarna_paynow"); } }
        public static PaymentMethodExtendedType Null { get { return new PaymentMethodExtendedType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(PaymentMethodExtendedType v) { return v.Value; }
        public static PaymentMethodExtendedType FromString(string v) {
            switch(v) {
                case "id": return Id;
                case "credit_card": return CreditCard;
                case "paypal": return Paypal;
                case "affirm": return Affirm;
                case "afterpay": return Afterpay;
                case "klarna": return Klarna;
                case "klarna_account": return KlarnaAccount;
                case "klarna_paynow": return KlarnaPaynow;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for PaymentMethodExtendedType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((PaymentMethodExtendedType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    [JsonConverter(typeof(PaymentMethodExtended.PaymentMethodExtendedConverter))]
    public class PaymentMethodExtended {
        public PaymentMethodExtended(PaymentMethodExtendedType type) {
            Type = type;
        }
        public PaymentMethodReference? PaymentMethodReference { get; set; }
        public PaymentMethodCreditCardInput? PaymentMethodCreditCardInput { get; set; }
        public PaymentMethodPaypal? PaymentMethodPaypal { get; set; }
        public PaymentMethodAffirm? PaymentMethodAffirm { get; set; }
        public PaymentMethodAfterpay? PaymentMethodAfterpay { get; set; }
        public PaymentMethodKlarna? PaymentMethodKlarna { get; set; }
        public PaymentMethodKlarnaAccount? PaymentMethodKlarnaAccount { get; set; }
        public PaymentMethodKlarnaPaynow? PaymentMethodKlarnaPaynow { get; set; }

        public PaymentMethodExtendedType Type { get; set; }


        public static PaymentMethodExtended CreateId(PaymentMethodReference id) {
            PaymentMethodExtendedType typ = PaymentMethodExtendedType.Id;
        
            string typStr = PaymentMethodExtendedType.Id.ToString();
            
            id.DotTag = PaymentMethodReferenceTagExtension.ToEnum(PaymentMethodExtendedType.Id.ToString());
            PaymentMethodExtended res = new PaymentMethodExtended(typ);
            res.PaymentMethodReference = id;
            return res;
        }
        public static PaymentMethodExtended CreateCreditCard(PaymentMethodCreditCardInput creditCard) {
            PaymentMethodExtendedType typ = PaymentMethodExtendedType.CreditCard;
        
            string typStr = PaymentMethodExtendedType.CreditCard.ToString();
            
            creditCard.DotTag = Models.Components.DotTagExtension.ToEnum(PaymentMethodExtendedType.CreditCard.ToString());
            PaymentMethodExtended res = new PaymentMethodExtended(typ);
            res.PaymentMethodCreditCardInput = creditCard;
            return res;
        }
        public static PaymentMethodExtended CreatePaypal(PaymentMethodPaypal paypal) {
            PaymentMethodExtendedType typ = PaymentMethodExtendedType.Paypal;
        
            string typStr = PaymentMethodExtendedType.Paypal.ToString();
            
            paypal.DotTag = PaymentMethodPaypalTagExtension.ToEnum(PaymentMethodExtendedType.Paypal.ToString());
            PaymentMethodExtended res = new PaymentMethodExtended(typ);
            res.PaymentMethodPaypal = paypal;
            return res;
        }
        public static PaymentMethodExtended CreateAffirm(PaymentMethodAffirm affirm) {
            PaymentMethodExtendedType typ = PaymentMethodExtendedType.Affirm;
        
            string typStr = PaymentMethodExtendedType.Affirm.ToString();
            
            affirm.DotTag = PaymentMethodAffirmTagExtension.ToEnum(PaymentMethodExtendedType.Affirm.ToString());
            PaymentMethodExtended res = new PaymentMethodExtended(typ);
            res.PaymentMethodAffirm = affirm;
            return res;
        }
        public static PaymentMethodExtended CreateAfterpay(PaymentMethodAfterpay afterpay) {
            PaymentMethodExtendedType typ = PaymentMethodExtendedType.Afterpay;
        
            string typStr = PaymentMethodExtendedType.Afterpay.ToString();
            
            afterpay.DotTag = PaymentMethodAfterpayTagExtension.ToEnum(PaymentMethodExtendedType.Afterpay.ToString());
            PaymentMethodExtended res = new PaymentMethodExtended(typ);
            res.PaymentMethodAfterpay = afterpay;
            return res;
        }
        public static PaymentMethodExtended CreateKlarna(PaymentMethodKlarna klarna) {
            PaymentMethodExtendedType typ = PaymentMethodExtendedType.Klarna;
        
            string typStr = PaymentMethodExtendedType.Klarna.ToString();
            
            klarna.DotTag = PaymentMethodKlarnaTagExtension.ToEnum(PaymentMethodExtendedType.Klarna.ToString());
            PaymentMethodExtended res = new PaymentMethodExtended(typ);
            res.PaymentMethodKlarna = klarna;
            return res;
        }
        public static PaymentMethodExtended CreateKlarnaAccount(PaymentMethodKlarnaAccount klarnaAccount) {
            PaymentMethodExtendedType typ = PaymentMethodExtendedType.KlarnaAccount;
        
            string typStr = PaymentMethodExtendedType.KlarnaAccount.ToString();
            
            klarnaAccount.DotTag = PaymentMethodKlarnaAccountTagExtension.ToEnum(PaymentMethodExtendedType.KlarnaAccount.ToString());
            PaymentMethodExtended res = new PaymentMethodExtended(typ);
            res.PaymentMethodKlarnaAccount = klarnaAccount;
            return res;
        }
        public static PaymentMethodExtended CreateKlarnaPaynow(PaymentMethodKlarnaPaynow klarnaPaynow) {
            PaymentMethodExtendedType typ = PaymentMethodExtendedType.KlarnaPaynow;
        
            string typStr = PaymentMethodExtendedType.KlarnaPaynow.ToString();
            
            klarnaPaynow.DotTag = PaymentMethodKlarnaPaynowTagExtension.ToEnum(PaymentMethodExtendedType.KlarnaPaynow.ToString());
            PaymentMethodExtended res = new PaymentMethodExtended(typ);
            res.PaymentMethodKlarnaPaynow = klarnaPaynow;
            return res;
        }
        public static PaymentMethodExtended CreateNull() {
            PaymentMethodExtendedType typ = PaymentMethodExtendedType.Null;
            return new PaymentMethodExtended(typ);
        }

        public class PaymentMethodExtendedConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(PaymentMethodExtended);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                JObject jo = JObject.Load(reader);
                string discriminator = jo.GetValue(".tag")?.ToString() ?? throw new ArgumentNullException("Could not find discriminator field.");
                if (discriminator == PaymentMethodExtendedType.Id.ToString())
                {
                    PaymentMethodReference? paymentMethodReference = ResponseBodyDeserializer.Deserialize<PaymentMethodReference>(jo.ToString());
                    return CreateId(paymentMethodReference!);
                }
                if (discriminator == PaymentMethodExtendedType.CreditCard.ToString())
                {
                    PaymentMethodCreditCardInput? paymentMethodCreditCardInput = ResponseBodyDeserializer.Deserialize<PaymentMethodCreditCardInput>(jo.ToString());
                    return CreateCreditCard(paymentMethodCreditCardInput!);
                }
                if (discriminator == PaymentMethodExtendedType.Paypal.ToString())
                {
                    PaymentMethodPaypal? paymentMethodPaypal = ResponseBodyDeserializer.Deserialize<PaymentMethodPaypal>(jo.ToString());
                    return CreatePaypal(paymentMethodPaypal!);
                }
                if (discriminator == PaymentMethodExtendedType.Affirm.ToString())
                {
                    PaymentMethodAffirm? paymentMethodAffirm = ResponseBodyDeserializer.Deserialize<PaymentMethodAffirm>(jo.ToString());
                    return CreateAffirm(paymentMethodAffirm!);
                }
                if (discriminator == PaymentMethodExtendedType.Afterpay.ToString())
                {
                    PaymentMethodAfterpay? paymentMethodAfterpay = ResponseBodyDeserializer.Deserialize<PaymentMethodAfterpay>(jo.ToString());
                    return CreateAfterpay(paymentMethodAfterpay!);
                }
                if (discriminator == PaymentMethodExtendedType.Klarna.ToString())
                {
                    PaymentMethodKlarna? paymentMethodKlarna = ResponseBodyDeserializer.Deserialize<PaymentMethodKlarna>(jo.ToString());
                    return CreateKlarna(paymentMethodKlarna!);
                }
                if (discriminator == PaymentMethodExtendedType.KlarnaAccount.ToString())
                {
                    PaymentMethodKlarnaAccount? paymentMethodKlarnaAccount = ResponseBodyDeserializer.Deserialize<PaymentMethodKlarnaAccount>(jo.ToString());
                    return CreateKlarnaAccount(paymentMethodKlarnaAccount!);
                }
                if (discriminator == PaymentMethodExtendedType.KlarnaPaynow.ToString())
                {
                    PaymentMethodKlarnaPaynow? paymentMethodKlarnaPaynow = ResponseBodyDeserializer.Deserialize<PaymentMethodKlarnaPaynow>(jo.ToString());
                    return CreateKlarnaPaynow(paymentMethodKlarnaPaynow!);
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                PaymentMethodExtended res = (PaymentMethodExtended)value;
                if (PaymentMethodExtendedType.FromString(res.Type).Equals(PaymentMethodExtendedType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.PaymentMethodReference != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.PaymentMethodReference));
                    return;
                }
                if (res.PaymentMethodCreditCardInput != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.PaymentMethodCreditCardInput));
                    return;
                }
                if (res.PaymentMethodPaypal != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.PaymentMethodPaypal));
                    return;
                }
                if (res.PaymentMethodAffirm != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.PaymentMethodAffirm));
                    return;
                }
                if (res.PaymentMethodAfterpay != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.PaymentMethodAfterpay));
                    return;
                }
                if (res.PaymentMethodKlarna != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.PaymentMethodKlarna));
                    return;
                }
                if (res.PaymentMethodKlarnaAccount != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.PaymentMethodKlarnaAccount));
                    return;
                }
                if (res.PaymentMethodKlarnaPaynow != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.PaymentMethodKlarnaPaynow));
                    return;
                }

            }

        }

    }
}