//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Boltpay.SDK.Models.Components
{
    using Boltpay.SDK.Models.Components;
    using Boltpay.SDK.Utils;
    using Newtonsoft.Json;
    
    public class PaymentMethodCreditCardInput
    {

        [JsonProperty(".tag")]
        public Models.Components.DotTag DotTag { get; set; } = default!;

        [JsonProperty("billing_address")]
        public AddressReferenceInput BillingAddress { get; set; } = default!;

        public AddressReferenceId? GetBillingAddressId()
        {
            return BillingAddress.AddressReferenceId;
        }

        public AddressReferenceExplicitInput? GetBillingAddressExplicit()
        {
            return BillingAddress.AddressReferenceExplicitInput;
        }

        /// <summary>
        /// The credit card&apos;s network.
        /// </summary>
        [JsonProperty("network")]
        public CreditCardNetwork Network { get; set; } = default!;

        /// <summary>
        /// The Bank Identification Number (BIN). This is typically the first 4 to 6 digits of the account number.
        /// </summary>
        [JsonProperty("bin")]
        public string Bin { get; set; } = default!;

        /// <summary>
        /// The account number&apos;s last four digits.
        /// </summary>
        [JsonProperty("last4")]
        public string Last4 { get; set; } = default!;

        /// <summary>
        /// The expiration date, in YYYY-MM format.
        /// </summary>
        [JsonProperty("expiration")]
        public string Expiration { get; set; } = default!;

        /// <summary>
        /// The Bolt token associated with the credit card.
        /// </summary>
        [JsonProperty("token")]
        public string Token { get; set; } = default!;
    }
}