//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Boltpay.SDK.Models.Components
{
    using Boltpay.SDK.Utils;
    
    public class Security
    {

        [SpeakeasyMetadata("security:scheme=true,type=oauth2,name=Authorization")]
        public string? Oauth { get; set; }

        [SpeakeasyMetadata("security:scheme=true,type=apiKey,subType=header,name=X-API-Key")]
        public string? ApiKey { get; set; }
    }
}