//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Boltpay.SDK.Models.Components
{
    using Boltpay.SDK.Models.Components;
    using Boltpay.SDK.Utils;
    using Newtonsoft.Json.Linq;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;
    using System;
    

    public class TokenRequestType
    {
        private TokenRequestType(string value) { Value = value; }

        public string Value { get; private set; }
        public static TokenRequestType AuthorizationCodeRequest { get { return new TokenRequestType("authorization-code-request"); } }
        
        public static TokenRequestType RefreshTokenRequest { get { return new TokenRequestType("refresh-token-request"); } }
        
        public static TokenRequestType Null { get { return new TokenRequestType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(TokenRequestType v) { return v.Value; }
        public static TokenRequestType FromString(string v) {
            switch(v) {
                case "authorization-code-request": return AuthorizationCodeRequest;
                case "refresh-token-request": return RefreshTokenRequest;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for TokenRequestType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((TokenRequestType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    [JsonConverter(typeof(TokenRequest.TokenRequestConverter))]
    public class TokenRequest {
        public TokenRequest(TokenRequestType type) {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public AuthorizationCodeRequest? AuthorizationCodeRequest { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public RefreshTokenRequest? RefreshTokenRequest { get; set; }

        public TokenRequestType Type { get; set; }


        public static TokenRequest CreateAuthorizationCodeRequest(AuthorizationCodeRequest authorizationCodeRequest) {
            TokenRequestType typ = TokenRequestType.AuthorizationCodeRequest;

            TokenRequest res = new TokenRequest(typ);
            res.AuthorizationCodeRequest = authorizationCodeRequest;
            return res;
        }

        public static TokenRequest CreateRefreshTokenRequest(RefreshTokenRequest refreshTokenRequest) {
            TokenRequestType typ = TokenRequestType.RefreshTokenRequest;

            TokenRequest res = new TokenRequest(typ);
            res.RefreshTokenRequest = refreshTokenRequest;
            return res;
        }

        public static TokenRequest CreateNull() {
            TokenRequestType typ = TokenRequestType.Null;
            return new TokenRequest(typ);
        }

        public class TokenRequestConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(TokenRequest);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                var json = JRaw.Create(reader).ToString();
                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new TokenRequest(TokenRequestType.AuthorizationCodeRequest)
                    {
                        AuthorizationCodeRequest = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<AuthorizationCodeRequest>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(AuthorizationCodeRequest), new TokenRequest(TokenRequestType.AuthorizationCodeRequest), "AuthorizationCodeRequest"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new TokenRequest(TokenRequestType.RefreshTokenRequest)
                    {
                        RefreshTokenRequest = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<RefreshTokenRequest>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(RefreshTokenRequest), new TokenRequest(TokenRequestType.RefreshTokenRequest), "RefreshTokenRequest"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                TokenRequest res = (TokenRequest)value;
                if (TokenRequestType.FromString(res.Type).Equals(TokenRequestType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.AuthorizationCodeRequest != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.AuthorizationCodeRequest));
                    return;
                }
                if (res.RefreshTokenRequest != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.RefreshTokenRequest));
                    return;
                }

            }

        }

    }
}