//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Boltpay.SDK.Models.Requests
{
    using Boltpay.SDK.Utils;
    
    public class GuestPaymentsActionSecurity
    {

        [SpeakeasyMetadata("security:scheme=true,type=apiKey,subType=header,name=X-API-Key")]
        public string ApiKey { get; set; } = default!;
    }
}