//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Boltpay.SDK.Models.Errors
{
    using Boltpay.SDK.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// The type of error returned
    /// </summary>
    public enum CartErrorTag
    {
        [JsonProperty("payment_already_exists")]
        PaymentAlreadyExists,
        [JsonProperty("currency_not_supported")]
        CurrencyNotSupported,
    }

    public static class CartErrorTagExtension
    {
        public static string Value(this CartErrorTag value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static CartErrorTag ToEnum(this string value)
        {
            foreach(var field in typeof(CartErrorTag).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is CartErrorTag)
                    {
                        return (CartErrorTag)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum CartErrorTag");
        }
    }

}