//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Boltpay.SDK.Models.Errors
{
    using Boltpay.SDK.Models.Errors;
    using Boltpay.SDK.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// An error that pertains to validation of a specific field in the request.
    /// </summary>
    public class FieldError : Exception
    {

        /// <summary>
        /// The type of error returned
        /// </summary>
        [JsonProperty(".tag")]
        public FieldErrorTag DotTag { get; set; } = default!;

        /// <summary>
        /// A human-readable error message, which might include information specific to the request that was made.
        /// </summary>
        [JsonProperty("message")]
        private string? _message { get; set; }
        public override string Message { get {return _message ?? "";} }

        /// <summary>
        /// The field (in its hierarchical form) that is failing validation.
        /// </summary>
        [JsonProperty("field")]
        public string Field { get; set; } = default!;
    }
}