//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Boltpay.SDK.Models.Errors
{
    using Boltpay.SDK.Models.Errors;
    using Boltpay.SDK.Utils;
    using Newtonsoft.Json.Linq;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;
    using System;
    

    public class Response4xxType
    {
        private Response4xxType(string value) { Value = value; }

        public string Value { get; private set; }
        public static Response4xxType Error { get { return new Response4xxType("error"); } }
        
        public static Response4xxType FieldError { get { return new Response4xxType("field-error"); } }
        
        public static Response4xxType Null { get { return new Response4xxType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(Response4xxType v) { return v.Value; }
        public static Response4xxType FromString(string v) {
            switch(v) {
                case "error": return Error;
                case "field-error": return FieldError;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for Response4xxType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((Response4xxType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    /// <summary>
    /// An error has occurred, and further details are contained in the response
    /// </summary>
    [JsonConverter(typeof(Response4xx.Response4xxConverter))]
    public class Response4xx {
        public Response4xx(Response4xxType type) {
            Type = type;
        }
        public Error? Error { get; set; }
        public FieldError? FieldError { get; set; }

        public Response4xxType Type { get; set; }


        public static Response4xx CreateError(Error error) {
            Response4xxType typ = Response4xxType.Error;

            Response4xx res = new Response4xx(typ);
            res.Error = error;
            return res;
        }

        public static Response4xx CreateFieldError(FieldError fieldError) {
            Response4xxType typ = Response4xxType.FieldError;

            Response4xx res = new Response4xx(typ);
            res.FieldError = fieldError;
            return res;
        }

        public static Response4xx CreateNull() {
            Response4xxType typ = Response4xxType.Null;
            return new Response4xx(typ);
        }

        public class Response4xxConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(Response4xx);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                var json = JRaw.Create(reader).ToString();
                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new Response4xx(Response4xxType.Error)
                    {
                        Error = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<Error>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(Error), new Response4xx(Response4xxType.Error), "Error"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new Response4xx(Response4xxType.FieldError)
                    {
                        FieldError = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<FieldError>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(FieldError), new Response4xx(Response4xxType.FieldError), "FieldError"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                Response4xx res = (Response4xx)value;
                if (Response4xxType.FromString(res.Type).Equals(Response4xxType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.Error != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Error));
                    return;
                }
                if (res.FieldError != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.FieldError));
                    return;
                }

            }

        }

    }
}