//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Boltpay.SDK.Models.Errors
{
    using Boltpay.SDK.Models.Errors;
    using Boltpay.SDK.Utils;
    using Newtonsoft.Json.Linq;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;
    using System;
    

    public class ResponsePaymentMethodErrorType
    {
        private ResponsePaymentMethodErrorType(string value) { Value = value; }

        public string Value { get; private set; }
        public static ResponsePaymentMethodErrorType Error { get { return new ResponsePaymentMethodErrorType("error"); } }
        
        public static ResponsePaymentMethodErrorType FieldError { get { return new ResponsePaymentMethodErrorType("field-error"); } }
        
        public static ResponsePaymentMethodErrorType CreditCardError { get { return new ResponsePaymentMethodErrorType("credit-card-error"); } }
        
        public static ResponsePaymentMethodErrorType Null { get { return new ResponsePaymentMethodErrorType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(ResponsePaymentMethodErrorType v) { return v.Value; }
        public static ResponsePaymentMethodErrorType FromString(string v) {
            switch(v) {
                case "error": return Error;
                case "field-error": return FieldError;
                case "credit-card-error": return CreditCardError;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for ResponsePaymentMethodErrorType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((ResponsePaymentMethodErrorType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    [JsonConverter(typeof(ResponsePaymentMethodError.ResponsePaymentMethodErrorConverter))]
    public class ResponsePaymentMethodError {
        public ResponsePaymentMethodError(ResponsePaymentMethodErrorType type) {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public Error? Error { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public FieldError? FieldError { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public CreditCardError? CreditCardError { get; set; }

        public ResponsePaymentMethodErrorType Type { get; set; }


        public static ResponsePaymentMethodError CreateError(Error error) {
            ResponsePaymentMethodErrorType typ = ResponsePaymentMethodErrorType.Error;

            ResponsePaymentMethodError res = new ResponsePaymentMethodError(typ);
            res.Error = error;
            return res;
        }

        public static ResponsePaymentMethodError CreateFieldError(FieldError fieldError) {
            ResponsePaymentMethodErrorType typ = ResponsePaymentMethodErrorType.FieldError;

            ResponsePaymentMethodError res = new ResponsePaymentMethodError(typ);
            res.FieldError = fieldError;
            return res;
        }

        public static ResponsePaymentMethodError CreateCreditCardError(CreditCardError creditCardError) {
            ResponsePaymentMethodErrorType typ = ResponsePaymentMethodErrorType.CreditCardError;

            ResponsePaymentMethodError res = new ResponsePaymentMethodError(typ);
            res.CreditCardError = creditCardError;
            return res;
        }

        public static ResponsePaymentMethodError CreateNull() {
            ResponsePaymentMethodErrorType typ = ResponsePaymentMethodErrorType.Null;
            return new ResponsePaymentMethodError(typ);
        }

        public class ResponsePaymentMethodErrorConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(ResponsePaymentMethodError);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                var json = JRaw.Create(reader).ToString();
                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new ResponsePaymentMethodError(ResponsePaymentMethodErrorType.Error)
                    {
                        Error = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<Error>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(Error), new ResponsePaymentMethodError(ResponsePaymentMethodErrorType.Error), "Error"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new ResponsePaymentMethodError(ResponsePaymentMethodErrorType.FieldError)
                    {
                        FieldError = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<FieldError>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(FieldError), new ResponsePaymentMethodError(ResponsePaymentMethodErrorType.FieldError), "FieldError"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new ResponsePaymentMethodError(ResponsePaymentMethodErrorType.CreditCardError)
                    {
                        CreditCardError = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<CreditCardError>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(CreditCardError), new ResponsePaymentMethodError(ResponsePaymentMethodErrorType.CreditCardError), "CreditCardError"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                ResponsePaymentMethodError res = (ResponsePaymentMethodError)value;
                if (ResponsePaymentMethodErrorType.FromString(res.Type).Equals(ResponsePaymentMethodErrorType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.Error != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Error));
                    return;
                }
                if (res.FieldError != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.FieldError));
                    return;
                }
                if (res.CreditCardError != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.CreditCardError));
                    return;
                }

            }

        }

    }
}