//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Boltpay.SDK.Models.Errors
{
    using Boltpay.SDK.Models.Errors;
    using Boltpay.SDK.Utils;
    using Newtonsoft.Json.Linq;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;
    using System;
    

    public class ResponseAddressErrorType
    {
        private ResponseAddressErrorType(string value) { Value = value; }

        public string Value { get; private set; }
        public static ResponseAddressErrorType Error { get { return new ResponseAddressErrorType("error"); } }
        
        public static ResponseAddressErrorType FieldError { get { return new ResponseAddressErrorType("field-error"); } }
        
        public static ResponseAddressErrorType Null { get { return new ResponseAddressErrorType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(ResponseAddressErrorType v) { return v.Value; }
        public static ResponseAddressErrorType FromString(string v) {
            switch(v) {
                case "error": return Error;
                case "field-error": return FieldError;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for ResponseAddressErrorType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((ResponseAddressErrorType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    /// <summary>
    /// The address is invalid and cannot be added, or some other error has occurred
    /// </summary>
    [JsonConverter(typeof(ResponseAddressError.ResponseAddressErrorConverter))]
    public class ResponseAddressError {
        public ResponseAddressError(ResponseAddressErrorType type) {
            Type = type;
        }
        public Error? Error { get; set; }
        public FieldError? FieldError { get; set; }

        public ResponseAddressErrorType Type { get; set; }


        public static ResponseAddressError CreateError(Error error) {
            ResponseAddressErrorType typ = ResponseAddressErrorType.Error;

            ResponseAddressError res = new ResponseAddressError(typ);
            res.Error = error;
            return res;
        }

        public static ResponseAddressError CreateFieldError(FieldError fieldError) {
            ResponseAddressErrorType typ = ResponseAddressErrorType.FieldError;

            ResponseAddressError res = new ResponseAddressError(typ);
            res.FieldError = fieldError;
            return res;
        }

        public static ResponseAddressError CreateNull() {
            ResponseAddressErrorType typ = ResponseAddressErrorType.Null;
            return new ResponseAddressError(typ);
        }

        public class ResponseAddressErrorConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(ResponseAddressError);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                var json = JRaw.Create(reader).ToString();
                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new ResponseAddressError(ResponseAddressErrorType.Error)
                    {
                        Error = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<Error>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(Error), new ResponseAddressError(ResponseAddressErrorType.Error), "Error"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new ResponseAddressError(ResponseAddressErrorType.FieldError)
                    {
                        FieldError = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<FieldError>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(FieldError), new ResponseAddressError(ResponseAddressErrorType.FieldError), "FieldError"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                ResponseAddressError res = (ResponseAddressError)value;
                if (ResponseAddressErrorType.FromString(res.Type).Equals(ResponseAddressErrorType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.Error != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Error));
                    return;
                }
                if (res.FieldError != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.FieldError));
                    return;
                }

            }

        }

    }
}